Tatianebelo
thiagobitencourt/webdev-1 pull request #18
Opened 2017-09-17 14:46 UTC by TatiBelo16

Atualizando tags

2017-09-18 10:22 UTC, thiagobitencourt requested changes

2017-09-18 10:22 UTC, thiagobitencourt commented on tatianebelo/index.html
> +	<a href= "file:///C:/Users/tatiana/webdev-1/tatianebelo/formulario.html"
O href do link neste caso deveria ter o caminho relativo do arquivo de destino e não o caminho absoluto. O caminho absoluto é desta forma que você colocou, ou seja, desde a pasta raiz do sistema operacional. Já o caminho relativo, se inicia a partir do diretório atual. Então, nesse seu caso o caminha relativo para o formulario.html seria apenas formulario.html já que esta no mesmo diretório que o arquivo index.html.

Se deixar desta forma, o link irá funcionar apenas no seu computador e somente se os arquivos estiverem exatamente no mesmo diretório absoluto. Então, para evitar esse problema, mude o link para o caminho relativo.

2017-09-18 10:22 UTC, thiagobitencourt commented on tatianebelo/index.html
> +	<img vspace="35px" hspace="15px" src="C:\Users\tatiana\webdev-1\tatianebelo.png"/>
Aqui também deveria ser o caminha relativo para a imagem

2017-09-18 10:23 UTC, thiagobitencourt requested changes

2017-09-18 10:23 UTC, thiagobitencourt commented on tatianebelo/debug.log
> +[0914/233417.819:ERROR:persistent_memory_allocator.cc(777)] Corruption detected in shared-memory segment.
adicione o arquivo debug.log ao seu arquivo .gitignore

2017-09-21 21:56 UTC, thiagobitencourt approved these changes

2017-09-21 21:56 UTC, merged

2017-09-21 21:59 UTC, TatiBelo16 commented on tatianebelo/index.html
> +	<a href= "file:///C:/Users/tatiana/webdev-1/tatianebelo/formulario.html"
ok

2017-09-21 21:59 UTC, TatiBelo16 commented on tatianebelo/index.html
> +	<img vspace="35px" hspace="15px" src="C:\Users\tatiana\webdev-1\tatianebelo.png"/>
ok, alterado.

2017-09-21 21:59 UTC, TatiBelo16 commented on tatianebelo/debug.log
> +[0914/233417.819:ERROR:persistent_memory_allocator.cc(777)] Corruption detected in shared-memory segment.
ok