Fabioholocheski
thiagobitencourt/webdev-1 pull request #29
Opened 2017-09-21 22:04 UTC by FabioHolocheski

Atividade 1

2017-09-22 00:23 UTC, thiagobitencourt requested changes
Algumas alterações são necessárias. Mas de modo geral ficou bom.

2017-09-22 00:23 UTC, thiagobitencourt commented on fabioholocheski/Parcial1/cadastro_perfil.html
> +    <header>
A tag `header` serve para separar o conteúdo que é de apresentação da página ou de uma seção e não deveria ter formulários.

Em vez de usar tags `<br />` para pular linhas, poderia organizar os conteúdos que você quer que fique agrupados em uma tag `<div>`

2017-09-26 00:19 UTC, thiagobitencourt commented
Estas considerações também valem para esta entrega: https://github.com/thiagobitencourt/webdev-1/pull/31

2017-10-02 23:55 UTC, FabioHolocheski commented on fabioholocheski/Parcial1/cadastro_perfil.html
> +    <header>
As alterações Necessárias foram feitas!

2017-10-03 10:37 UTC, thiagobitencourt approved these changes

2017-10-07 01:12 UTC, merged