Atividade 1 Luizfernandokazmirski
thiagobitencourt/webdev-1 pull request #33
Opened 2017-09-21 22:16 UTC by NandoLFK

2017-09-25 16:57 UTC, thiagobitencourt requested changes

2017-09-25 16:57 UTC, thiagobitencourt commented on luizfernandokazmirski/perfil.html
> +		<h2>Meu Perfil</h2>
Poderia fazer um pouco mais de uso das tags semânticas e também é legal identar o código html.

2017-09-25 19:55 UTC, NandoLFK commented
Ok

Obrigado pelas dicas. Vou seguir.

2017-09-25 13:57 GMT-03:00 Thiago Bitencourt <notifications@github.com>:

> *@thiagobitencourt* requested changes on this pull request.
> ------------------------------
>
> In luizfernandokazmirski/perfil.html
> <https://github.com/thiagobitencourt/webdev-1/pull/33#discussion_r140834942>
> :
>
> > @@ -0,0 +1,38 @@
> +<!DOCTYPE html>
> +<html>
> +	<head>
> +		
> +		<title>
> +			Meu Perfil
> +		</title>
> +		<body>
> +		<h2>Meu Perfil</h2>
>
> Poderia fazer um pouco mais de uso das tags semânticas e também é legal
> identar o código html.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/thiagobitencourt/webdev-1/pull/33#pullrequestreview-64964232>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AbmNm6id1xPbcf-hjy2JsEEoWSL2-7nyks5sl9uFgaJpZM4Pf_P6>
> .
>

2017-10-07 01:14 UTC, thiagobitencourt approved these changes

2017-10-07 01:14 UTC, merged